Update 02_headers.md
githubtraining/communicating-using-markdown pull request #39
Opened 2021-07-13 02:25 UTC by nemophila1998

Hello!
Thank you very much for your fun work!
Very good lesson for beginners to learn GitHub, so please fix to follow instructions smoothly.

2021-07-13 14:17 UTC, brianamarie requested changes
Hello @nemophila1998! Thank you for this improvement.

I've suggested a change from meatball, and also removing hamburger, to something hopefully more universally descriptive. What do you think?

2021-07-13 14:17 UTC, brianamarie commented on responses/02_headers.md
> +1. To edit the file titled `_includes/01-name.md`, click the **small pencil** ✏️ or select "Edit file" from the **meatballs ...** menu in the upper right corner of the file view.
```suggestion
1. To edit the file titled `_includes/01-name.md`, click the **small pencil** ✏️ or select "Edit file" from the three dotted **...** menu in the upper right corner of the file view.
```

2021-07-14 04:17 UTC, nemophila1998 commented
Hello.
I think it's good. Thanks.

2021-07-14 12:45 UTC, brianamarie approved these changes
Thank you so much, @nemophila1998!

2021-07-14 12:46 UTC, merged